// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalog.Database.Context;

namespace MovieCatalog.Migrations.CatalogMigrations
{
    [DbContext(typeof(Catalog))]
    partial class CatalogModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MovieCatalog.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProducedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Odit omnis ipsum placeat nisi corrupti.\nPlaceat magnam aspernatur neque assumenda accusamus sit optio sint.\nMollitia corrupti dolor consequatur ut aut exercitationem consequatur illo.\nSoluta hic similique est voluptatibus aut sint et sed.\nLaborum quia ratione tenetur enim.\nLaboriosam enim ut sed vero aperiam earum ducimus nostrum perferendis.",
                            Name = "eos-quis-rerum",
                            Poster = "https://picsum.photos/640/480/?image=810",
                            ProducedDate = new DateTime(2020, 3, 19, 3, 45, 7, 572, DateTimeKind.Local).AddTicks(1953),
                            Producer = "Beier Rolando",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nobis ducimus dolor quibusdam hic explicabo in nam tempora.\nLaboriosam modi illo quia laudantium voluptatibus.",
                            Name = "officiis-quod-quis",
                            Poster = "https://picsum.photos/640/480/?image=699",
                            ProducedDate = new DateTime(2020, 10, 16, 22, 10, 25, 546, DateTimeKind.Local).AddTicks(9494),
                            Producer = "Stanton Agustin",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vitae quis vel officiis fugiat provident vel molestias quaerat. Dolores odit magnam omnis blanditiis ad eius illum tempore blanditiis. Sint veniam necessitatibus. Odio mollitia dolores autem error sunt numquam quas.",
                            Name = "consequatur-sed-ea",
                            Poster = "https://picsum.photos/640/480/?image=307",
                            ProducedDate = new DateTime(2020, 10, 20, 15, 58, 36, 975, DateTimeKind.Local).AddTicks(8322),
                            Producer = "Anderson Constance",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Veritatis sunt pariatur asperiores mollitia aliquam amet.",
                            Name = "ex-rerum-consequatur",
                            Poster = "https://picsum.photos/640/480/?image=319",
                            ProducedDate = new DateTime(2020, 2, 29, 13, 33, 9, 363, DateTimeKind.Local).AddTicks(8579),
                            Producer = "Turcotte Kane",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 5,
                            Description = "corrupti",
                            Name = "fugiat-at-similique",
                            Poster = "https://picsum.photos/640/480/?image=344",
                            ProducedDate = new DateTime(2020, 8, 29, 14, 27, 22, 529, DateTimeKind.Local).AddTicks(7691),
                            Producer = "Huels Tremaine",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Placeat magnam asperiores et. Et quae praesentium qui. Ipsa facilis voluptas laboriosam nemo veritatis distinctio unde. Libero labore dignissimos fugit autem sed dolore officiis explicabo eum. Est non reprehenderit iusto molestias.",
                            Name = "porro-optio-et",
                            Poster = "https://picsum.photos/640/480/?image=394",
                            ProducedDate = new DateTime(2019, 12, 17, 2, 15, 12, 321, DateTimeKind.Local).AddTicks(3837),
                            Producer = "Ritchie Alfreda",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 7,
                            Description = "vel",
                            Name = "et-temporibus-qui",
                            Poster = "https://picsum.photos/640/480/?image=645",
                            ProducedDate = new DateTime(2020, 6, 12, 10, 36, 20, 82, DateTimeKind.Local).AddTicks(3544),
                            Producer = "McLaughlin Kathlyn",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Recusandae et corporis.",
                            Name = "aut-expedita-aperiam",
                            Poster = "https://picsum.photos/640/480/?image=1011",
                            ProducedDate = new DateTime(2020, 10, 4, 20, 53, 29, 23, DateTimeKind.Local).AddTicks(1131),
                            Producer = "Donnelly Nathan",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 9,
                            Description = "itaque",
                            Name = "doloribus-hic-et",
                            Poster = "https://picsum.photos/640/480/?image=904",
                            ProducedDate = new DateTime(2020, 10, 13, 20, 11, 25, 500, DateTimeKind.Local).AddTicks(6554),
                            Producer = "Funk Gunner",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 10,
                            Description = "corrupti",
                            Name = "quis-voluptatem-fuga",
                            Poster = "https://picsum.photos/640/480/?image=800",
                            ProducedDate = new DateTime(2020, 1, 7, 0, 5, 53, 224, DateTimeKind.Local).AddTicks(9307),
                            Producer = "Spinka Eryn",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Quia sit occaecati.",
                            Name = "ut-non-optio",
                            Poster = "https://picsum.photos/640/480/?image=220",
                            ProducedDate = new DateTime(2019, 12, 19, 0, 1, 40, 972, DateTimeKind.Local).AddTicks(8756),
                            Producer = "Klocko Jordyn",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Voluptas assumenda doloremque odio suscipit laboriosam.",
                            Name = "et-ut-nostrum",
                            Poster = "https://picsum.photos/640/480/?image=363",
                            ProducedDate = new DateTime(2020, 10, 1, 8, 27, 47, 749, DateTimeKind.Local).AddTicks(6866),
                            Producer = "Rowe Louie",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 13,
                            Description = "beatae",
                            Name = "voluptate-et-excepturi",
                            Poster = "https://picsum.photos/640/480/?image=234",
                            ProducedDate = new DateTime(2019, 12, 3, 12, 38, 6, 840, DateTimeKind.Local).AddTicks(3614),
                            Producer = "Jacobi Royal",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Quam sit quibusdam necessitatibus harum sunt dolor suscipit facere.",
                            Name = "ut-quo-et",
                            Poster = "https://picsum.photos/640/480/?image=328",
                            ProducedDate = new DateTime(2020, 11, 5, 18, 45, 46, 904, DateTimeKind.Local).AddTicks(1087),
                            Producer = "Batz April",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Quo et qui quam in iusto.\nEa est architecto adipisci.\nAut enim ad voluptatem sequi ut aliquam magni.\nIste architecto ipsam.",
                            Name = "exercitationem-aut-consectetur",
                            Poster = "https://picsum.photos/640/480/?image=726",
                            ProducedDate = new DateTime(2020, 6, 6, 16, 57, 6, 353, DateTimeKind.Local).AddTicks(6928),
                            Producer = "Auer Abraham",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Et eum ut omnis qui qui.\nIpsum sunt quaerat natus quia et.",
                            Name = "aut-nulla-accusantium",
                            Poster = "https://picsum.photos/640/480/?image=924",
                            ProducedDate = new DateTime(2020, 2, 18, 17, 52, 29, 400, DateTimeKind.Local).AddTicks(2945),
                            Producer = "Barrows Dovie",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Pariatur eos tenetur vel et.",
                            Name = "est-exercitationem-iure",
                            Poster = "https://picsum.photos/640/480/?image=55",
                            ProducedDate = new DateTime(2020, 5, 2, 3, 33, 24, 882, DateTimeKind.Local).AddTicks(6776),
                            Producer = "Gutkowski Rosalyn",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Qui ratione et.\nSaepe laudantium illum facere qui tenetur et rerum.\nAsperiores autem reprehenderit consequatur aperiam suscipit voluptatibus fugiat consequatur.\nVoluptatem quo accusamus.",
                            Name = "molestias-non-iste",
                            Poster = "https://picsum.photos/640/480/?image=859",
                            ProducedDate = new DateTime(2020, 8, 25, 14, 23, 32, 500, DateTimeKind.Local).AddTicks(1790),
                            Producer = "DuBuque Amber",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 19,
                            Description = "praesentium",
                            Name = "molestias-et-qui",
                            Poster = "https://picsum.photos/640/480/?image=533",
                            ProducedDate = new DateTime(2020, 5, 22, 22, 17, 13, 23, DateTimeKind.Local).AddTicks(6163),
                            Producer = "Kulas Madie",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Sint voluptatum at tempore. Quisquam cupiditate commodi. Eius qui magni dolor saepe voluptatem. Est nihil aliquid dignissimos.",
                            Name = "illum-doloremque-eum",
                            Poster = "https://picsum.photos/640/480/?image=579",
                            ProducedDate = new DateTime(2020, 9, 19, 2, 3, 25, 588, DateTimeKind.Local).AddTicks(3188),
                            Producer = "Beer Laverne",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Qui repellat officia quo sint qui reprehenderit provident recusandae quasi.\nNihil sed aut officiis autem quo voluptas totam mollitia quam.\nLaudantium maiores consequatur eos debitis voluptatem et eius.\nVoluptatibus nulla excepturi voluptas officia ut earum.",
                            Name = "officiis-ut-sequi",
                            Poster = "https://picsum.photos/640/480/?image=84",
                            ProducedDate = new DateTime(2019, 12, 3, 14, 41, 6, 84, DateTimeKind.Local).AddTicks(9305),
                            Producer = "Murazik Reynold",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Officia distinctio dolores amet reprehenderit quasi et provident est sed.",
                            Name = "assumenda-minima-praesentium",
                            Poster = "https://picsum.photos/640/480/?image=561",
                            ProducedDate = new DateTime(2020, 4, 16, 20, 29, 48, 258, DateTimeKind.Local).AddTicks(8564),
                            Producer = "Simonis Andres",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Est et veniam fugiat assumenda autem voluptas assumenda nisi.\nSit non provident et quis distinctio nemo doloremque quia voluptates.",
                            Name = "architecto-qui-porro",
                            Poster = "https://picsum.photos/640/480/?image=59",
                            ProducedDate = new DateTime(2019, 12, 21, 2, 37, 16, 531, DateTimeKind.Local).AddTicks(4826),
                            Producer = "Wuckert Zaria",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 24,
                            Description = "facere",
                            Name = "itaque-fugit-repudiandae",
                            Poster = "https://picsum.photos/640/480/?image=491",
                            ProducedDate = new DateTime(2020, 7, 19, 8, 48, 50, 295, DateTimeKind.Local).AddTicks(3916),
                            Producer = "Bednar Olga",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Quam animi incidunt voluptatem amet et aliquid beatae.",
                            Name = "et-sit-ut",
                            Poster = "https://picsum.photos/640/480/?image=450",
                            ProducedDate = new DateTime(2020, 8, 6, 18, 43, 6, 986, DateTimeKind.Local).AddTicks(191),
                            Producer = "Conn Danny",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 26,
                            Description = "recusandae",
                            Name = "nihil-nobis-sit",
                            Poster = "https://picsum.photos/640/480/?image=970",
                            ProducedDate = new DateTime(2020, 4, 7, 15, 16, 59, 149, DateTimeKind.Local).AddTicks(2197),
                            Producer = "Friesen Daphney",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 27,
                            Description = "asperiores",
                            Name = "et-debitis-minus",
                            Poster = "https://picsum.photos/640/480/?image=994",
                            ProducedDate = new DateTime(2020, 1, 16, 16, 10, 5, 680, DateTimeKind.Local).AddTicks(5674),
                            Producer = "Jenkins Antwon",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Soluta est autem magni nihil eos illum.\nAut laboriosam et quis odio ea soluta cumque aspernatur.\nAssumenda assumenda quisquam dolores.\nConsectetur aut itaque alias.\nPerspiciatis veniam dolores dolor beatae possimus.",
                            Name = "deserunt-earum-veniam",
                            Poster = "https://picsum.photos/640/480/?image=127",
                            ProducedDate = new DateTime(2020, 6, 24, 19, 14, 7, 889, DateTimeKind.Local).AddTicks(2202),
                            Producer = "Cronin Roberto",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 29,
                            Description = "pariatur",
                            Name = "cupiditate-doloremque-quo",
                            Poster = "https://picsum.photos/640/480/?image=1053",
                            ProducedDate = new DateTime(2020, 3, 20, 5, 43, 54, 226, DateTimeKind.Local).AddTicks(2732),
                            Producer = "Bins Jaydon",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Voluptas at sit rerum animi sed voluptas eos iusto. Mollitia quia eos nostrum. Earum occaecati et voluptatibus dolorum id non et.",
                            Name = "porro-ut-necessitatibus",
                            Poster = "https://picsum.photos/640/480/?image=575",
                            ProducedDate = new DateTime(2020, 3, 31, 13, 50, 6, 966, DateTimeKind.Local).AddTicks(5998),
                            Producer = "Klocko Blair",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Voluptates ut ut incidunt occaecati ut repellat omnis ipsum in.\nMagnam rem recusandae amet quis est quo voluptatem et.\nDolores voluptates ut sed sit atque officia.\nSunt nostrum in nesciunt non tempora inventore repellendus quo.",
                            Name = "ut-quis-ratione",
                            Poster = "https://picsum.photos/640/480/?image=933",
                            ProducedDate = new DateTime(2020, 11, 23, 8, 43, 55, 735, DateTimeKind.Local).AddTicks(5367),
                            Producer = "Nader Willow",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Amet nisi soluta sint et harum sunt deleniti omnis quia.",
                            Name = "error-provident-maxime",
                            Poster = "https://picsum.photos/640/480/?image=815",
                            ProducedDate = new DateTime(2020, 3, 25, 5, 56, 54, 16, DateTimeKind.Local).AddTicks(4562),
                            Producer = "Powlowski Ethyl",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 33,
                            Description = "ullam",
                            Name = "voluptate-sapiente-animi",
                            Poster = "https://picsum.photos/640/480/?image=142",
                            ProducedDate = new DateTime(2020, 10, 20, 5, 45, 52, 589, DateTimeKind.Local).AddTicks(7935),
                            Producer = "Gislason Meaghan",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Expedita similique vel quos qui velit exercitationem dolore fugit illo.",
                            Name = "quas-inventore-quo",
                            Poster = "https://picsum.photos/640/480/?image=790",
                            ProducedDate = new DateTime(2020, 1, 13, 20, 2, 23, 143, DateTimeKind.Local).AddTicks(8710),
                            Producer = "Welch Kyla",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 35,
                            Description = "nam",
                            Name = "qui-minus-sed",
                            Poster = "https://picsum.photos/640/480/?image=1048",
                            ProducedDate = new DateTime(2020, 1, 6, 1, 42, 49, 812, DateTimeKind.Local).AddTicks(8968),
                            Producer = "Marvin Spencer",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Dolor blanditiis porro labore.\nDolorem quia rerum ipsum omnis dolores blanditiis neque.\nPerspiciatis magnam ex molestias sed magnam in eum ipsa.\nExcepturi nemo possimus.",
                            Name = "nihil-ducimus-corporis",
                            Poster = "https://picsum.photos/640/480/?image=911",
                            ProducedDate = new DateTime(2020, 4, 16, 20, 9, 39, 928, DateTimeKind.Local).AddTicks(898),
                            Producer = "Williamson Alvina",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Nihil saepe et dolore. Rerum laudantium non molestiae velit ab nihil quia explicabo. Amet tempora vel autem esse libero qui eum et. Maiores consequuntur quo expedita quidem quia voluptates. Odit est laborum et consequatur laborum iusto in cupiditate vitae.",
                            Name = "deleniti-illum-eaque",
                            Poster = "https://picsum.photos/640/480/?image=851",
                            ProducedDate = new DateTime(2019, 12, 31, 8, 27, 21, 245, DateTimeKind.Local).AddTicks(5725),
                            Producer = "Quitzon Chet",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Sit voluptatum aut excepturi.\nFacilis et qui placeat officiis temporibus quis eos voluptatum.\nDignissimos dolor iste.",
                            Name = "tenetur-quae-exercitationem",
                            Poster = "https://picsum.photos/640/480/?image=911",
                            ProducedDate = new DateTime(2020, 9, 2, 21, 33, 9, 403, DateTimeKind.Local).AddTicks(1495),
                            Producer = "Dooley Florence",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Sed quia libero ea ab eveniet.",
                            Name = "ratione-facilis-atque",
                            Poster = "https://picsum.photos/640/480/?image=732",
                            ProducedDate = new DateTime(2020, 2, 16, 1, 38, 58, 669, DateTimeKind.Local).AddTicks(5349),
                            Producer = "Runolfsson Lora",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Est exercitationem est similique nihil porro excepturi et quod. Accusantium repellendus laboriosam voluptas voluptas. Deleniti eius animi. Vitae excepturi quod iure quis impedit et assumenda. Omnis eos reprehenderit.",
                            Name = "aut-autem-commodi",
                            Poster = "https://picsum.photos/640/480/?image=379",
                            ProducedDate = new DateTime(2020, 2, 26, 15, 3, 26, 178, DateTimeKind.Local).AddTicks(7605),
                            Producer = "Ankunding Jerome",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Et dolorum soluta officiis maiores nihil corporis ut.",
                            Name = "debitis-temporibus-porro",
                            Poster = "https://picsum.photos/640/480/?image=230",
                            ProducedDate = new DateTime(2020, 10, 27, 21, 25, 26, 8, DateTimeKind.Local).AddTicks(6786),
                            Producer = "Haley Bryce",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Asperiores quis quod temporibus.\nQuas quidem quae voluptas fugiat reiciendis voluptatem est quas fugit.\nVeniam saepe inventore sint iure quis magni quam consequatur ducimus.",
                            Name = "ut-maxime-eos",
                            Poster = "https://picsum.photos/640/480/?image=292",
                            ProducedDate = new DateTime(2020, 3, 5, 14, 19, 10, 49, DateTimeKind.Local).AddTicks(7237),
                            Producer = "Daugherty Odie",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Et perferendis rerum dolor.\nEarum aspernatur rem consequatur.\nFuga rerum aspernatur maiores laudantium et et nihil vel impedit.\nVoluptatem dolor provident temporibus.\nAd inventore voluptatum amet quos aspernatur.",
                            Name = "ea-autem-expedita",
                            Poster = "https://picsum.photos/640/480/?image=291",
                            ProducedDate = new DateTime(2020, 2, 11, 16, 36, 53, 596, DateTimeKind.Local).AddTicks(4323),
                            Producer = "Von Anika",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Distinctio illo dicta qui.",
                            Name = "magnam-aut-ad",
                            Poster = "https://picsum.photos/640/480/?image=875",
                            ProducedDate = new DateTime(2020, 10, 25, 16, 50, 19, 642, DateTimeKind.Local).AddTicks(8049),
                            Producer = "Bode Otha",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Animi incidunt aut. Repellendus nam eaque repellat dolor molestiae. Vero dolor et adipisci doloribus dolorum molestiae.",
                            Name = "fugit-exercitationem-tenetur",
                            Poster = "https://picsum.photos/640/480/?image=288",
                            ProducedDate = new DateTime(2020, 7, 11, 17, 16, 54, 760, DateTimeKind.Local).AddTicks(9402),
                            Producer = "Ledner Jeromy",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Magnam ea saepe ut quia assumenda.",
                            Name = "optio-impedit-impedit",
                            Poster = "https://picsum.photos/640/480/?image=155",
                            ProducedDate = new DateTime(2020, 1, 8, 9, 0, 25, 258, DateTimeKind.Local).AddTicks(7466),
                            Producer = "Kohler Alia",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 47,
                            Description = "nam",
                            Name = "corrupti-quos-dolor",
                            Poster = "https://picsum.photos/640/480/?image=238",
                            ProducedDate = new DateTime(2020, 1, 8, 13, 57, 11, 684, DateTimeKind.Local).AddTicks(3257),
                            Producer = "O'Kon Elias",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 48,
                            Description = "tempore",
                            Name = "ut-vero-laborum",
                            Poster = "https://picsum.photos/640/480/?image=592",
                            ProducedDate = new DateTime(2020, 5, 14, 21, 55, 52, 925, DateTimeKind.Local).AddTicks(7422),
                            Producer = "Jaskolski Jeffery",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Temporibus quidem quis necessitatibus.\nSunt nemo praesentium sequi.\nMagni recusandae officia autem fugiat reprehenderit eaque velit corrupti.\nHarum quidem incidunt eius perferendis sint.",
                            Name = "sit-sed-in",
                            Poster = "https://picsum.photos/640/480/?image=544",
                            ProducedDate = new DateTime(2020, 8, 12, 19, 1, 32, 387, DateTimeKind.Local).AddTicks(9237),
                            Producer = "Harber Brendan",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Qui voluptas aspernatur.\nMollitia in praesentium minima.\nDeserunt qui fugit quo earum dolores doloribus.",
                            Name = "quod-consequatur-dicta",
                            Poster = "https://picsum.photos/640/480/?image=164",
                            ProducedDate = new DateTime(2020, 9, 14, 2, 14, 4, 436, DateTimeKind.Local).AddTicks(6038),
                            Producer = "Watsica Kali",
                            UserId = "2de669e9-5643-4695-8189-aa5a589d9a70"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
